apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: prefer-family
spec:
  priorities:
  - machineFamily: c4
    minCores: 4
  - machineFamily: c3d
    minCores: 4
  autoscalingPolicy:
    consolidationDelayMinutes: 1
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
